// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: federation.proto

package federationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FederationService_Health_FullMethodName         = "/federation.v1.FederationService/Health"
	FederationService_CheckDuplicate_FullMethodName = "/federation.v1.FederationService/CheckDuplicate"
	FederationService_UploadFile_FullMethodName     = "/federation.v1.FederationService/UploadFile"
	FederationService_DownloadFile_FullMethodName   = "/federation.v1.FederationService/DownloadFile"
	FederationService_ListObjects_FullMethodName    = "/federation.v1.FederationService/ListObjects"
)

// FederationServiceClient is the client API for FederationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationServiceClient interface {
	// Health check for MinIO and service.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Check if a file with given SHA256 already exists (duplicate detection).
	CheckDuplicate(ctx context.Context, in *CheckDuplicateRequest, opts ...grpc.CallOption) (*CheckDuplicateResponse, error)
	// Upload a file (streaming). Rejects if duplicate SHA256 when reject_duplicate is true.
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (FederationService_UploadFileClient, error)
	// Download a file by object key (streaming).
	DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (FederationService_DownloadFileClient, error)
	// List objects in a bucket (optional prefix).
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
}

type federationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationServiceClient(cc grpc.ClientConnInterface) FederationServiceClient {
	return &federationServiceClient{cc}
}

func (c *federationServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, FederationService_Health_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) CheckDuplicate(ctx context.Context, in *CheckDuplicateRequest, opts ...grpc.CallOption) (*CheckDuplicateResponse, error) {
	out := new(CheckDuplicateResponse)
	err := c.cc.Invoke(ctx, FederationService_CheckDuplicate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federationServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (FederationService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[0], FederationService_UploadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &federationServiceUploadFileClient{stream}
	return x, nil
}

type FederationService_UploadFileClient interface {
	Send(*UploadChunk) error
	CloseAndRecv() (*UploadResponse, error)
	grpc.ClientStream
}

type federationServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *federationServiceUploadFileClient) Send(m *UploadChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *federationServiceUploadFileClient) CloseAndRecv() (*UploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *federationServiceClient) DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (FederationService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FederationService_ServiceDesc.Streams[1], FederationService_DownloadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &federationServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FederationService_DownloadFileClient interface {
	Recv() (*DownloadChunk, error)
	grpc.ClientStream
}

type federationServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *federationServiceDownloadFileClient) Recv() (*DownloadChunk, error) {
	m := new(DownloadChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *federationServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, FederationService_ListObjects_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederationServiceServer is the server API for FederationService service.
// All implementations must embed UnimplementedFederationServiceServer
// for forward compatibility
type FederationServiceServer interface {
	// Health check for MinIO and service.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Check if a file with given SHA256 already exists (duplicate detection).
	CheckDuplicate(context.Context, *CheckDuplicateRequest) (*CheckDuplicateResponse, error)
	// Upload a file (streaming). Rejects if duplicate SHA256 when reject_duplicate is true.
	UploadFile(FederationService_UploadFileServer) error
	// Download a file by object key (streaming).
	DownloadFile(*DownloadRequest, FederationService_DownloadFileServer) error
	// List objects in a bucket (optional prefix).
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	mustEmbedUnimplementedFederationServiceServer()
}

// UnimplementedFederationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFederationServiceServer struct {
}

func (UnimplementedFederationServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFederationServiceServer) CheckDuplicate(context.Context, *CheckDuplicateRequest) (*CheckDuplicateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDuplicate not implemented")
}
func (UnimplementedFederationServiceServer) UploadFile(FederationService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFederationServiceServer) DownloadFile(*DownloadRequest, FederationService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedFederationServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedFederationServiceServer) mustEmbedUnimplementedFederationServiceServer() {}

// UnsafeFederationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationServiceServer will
// result in compilation errors.
type UnsafeFederationServiceServer interface {
	mustEmbedUnimplementedFederationServiceServer()
}

func RegisterFederationServiceServer(s grpc.ServiceRegistrar, srv FederationServiceServer) {
	s.RegisterService(&FederationService_ServiceDesc, srv)
}

func _FederationService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_CheckDuplicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDuplicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).CheckDuplicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_CheckDuplicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).CheckDuplicate(ctx, req.(*CheckDuplicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederationService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FederationServiceServer).UploadFile(&federationServiceUploadFileServer{stream})
}

type FederationService_UploadFileServer interface {
	SendAndClose(*UploadResponse) error
	Recv() (*UploadChunk, error)
	grpc.ServerStream
}

type federationServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *federationServiceUploadFileServer) SendAndClose(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *federationServiceUploadFileServer) Recv() (*UploadChunk, error) {
	m := new(UploadChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FederationService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FederationServiceServer).DownloadFile(m, &federationServiceDownloadFileServer{stream})
}

type FederationService_DownloadFileServer interface {
	Send(*DownloadChunk) error
	grpc.ServerStream
}

type federationServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *federationServiceDownloadFileServer) Send(m *DownloadChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _FederationService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederationServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederationService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederationServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FederationService_ServiceDesc is the grpc.ServiceDesc for FederationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "federation.v1.FederationService",
	HandlerType: (*FederationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _FederationService_Health_Handler,
		},
		{
			MethodName: "CheckDuplicate",
			Handler:    _FederationService_CheckDuplicate_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _FederationService_ListObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FederationService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _FederationService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "federation.proto",
}
