# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import federation_pb2 as federation__pb2


class FederationServiceStub(object):
    """FederationService provides file storage and retrieval for the medical image federation.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/federation.v1.FederationService/Health',
                request_serializer=federation__pb2.HealthRequest.SerializeToString,
                response_deserializer=federation__pb2.HealthResponse.FromString,
                )
        self.CheckDuplicate = channel.unary_unary(
                '/federation.v1.FederationService/CheckDuplicate',
                request_serializer=federation__pb2.CheckDuplicateRequest.SerializeToString,
                response_deserializer=federation__pb2.CheckDuplicateResponse.FromString,
                )
        self.UploadFile = channel.stream_unary(
                '/federation.v1.FederationService/UploadFile',
                request_serializer=federation__pb2.UploadChunk.SerializeToString,
                response_deserializer=federation__pb2.UploadResponse.FromString,
                )
        self.DownloadFile = channel.unary_stream(
                '/federation.v1.FederationService/DownloadFile',
                request_serializer=federation__pb2.DownloadRequest.SerializeToString,
                response_deserializer=federation__pb2.DownloadChunk.FromString,
                )
        self.ListObjects = channel.unary_unary(
                '/federation.v1.FederationService/ListObjects',
                request_serializer=federation__pb2.ListObjectsRequest.SerializeToString,
                response_deserializer=federation__pb2.ListObjectsResponse.FromString,
                )
        self.ListPeers = channel.unary_unary(
                '/federation.v1.FederationService/ListPeers',
                request_serializer=federation__pb2.ListPeersRequest.SerializeToString,
                response_deserializer=federation__pb2.ListPeersResponse.FromString,
                )
        self.TransferFile = channel.unary_unary(
                '/federation.v1.FederationService/TransferFile',
                request_serializer=federation__pb2.TransferFileRequest.SerializeToString,
                response_deserializer=federation__pb2.TransferFileResponse.FromString,
                )
        self.PeerHealth = channel.unary_unary(
                '/federation.v1.FederationService/PeerHealth',
                request_serializer=federation__pb2.PeerHealthRequest.SerializeToString,
                response_deserializer=federation__pb2.PeerHealthResponse.FromString,
                )
        self.AddPeer = channel.unary_unary(
                '/federation.v1.FederationService/AddPeer',
                request_serializer=federation__pb2.AddPeerRequest.SerializeToString,
                response_deserializer=federation__pb2.AddPeerResponse.FromString,
                )
        self.GetNodeInfo = channel.unary_unary(
                '/federation.v1.FederationService/GetNodeInfo',
                request_serializer=federation__pb2.GetNodeInfoRequest.SerializeToString,
                response_deserializer=federation__pb2.GetNodeInfoResponse.FromString,
                )


class FederationServiceServicer(object):
    """FederationService provides file storage and retrieval for the medical image federation.
    """

    def Health(self, request, context):
        """Health check for MinIO and service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckDuplicate(self, request, context):
        """Check if a file with given SHA256 already exists (duplicate detection).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request_iterator, context):
        """Upload a file (streaming). Rejects if duplicate SHA256 when reject_duplicate is true.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Download a file by object key (streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """List objects in a bucket (optional prefix).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPeers(self, request, context):
        """── libp2p peer-discovery & cross-hospital transfer ──

        List peers discovered via libp2p mDNS / explicit bootstrap.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferFile(self, request, context):
        """Transfer a file to a remote hospital via libp2p stream (replaces HTTP POST).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PeerHealth(self, request, context):
        """Check health of a specific remote peer via libp2p stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPeer(self, request, context):
        """Tell the Go sidecar about a remote peer to connect to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeInfo(self, request, context):
        """Get this node's libp2p peer ID and listen addresses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=federation__pb2.HealthRequest.FromString,
                    response_serializer=federation__pb2.HealthResponse.SerializeToString,
            ),
            'CheckDuplicate': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckDuplicate,
                    request_deserializer=federation__pb2.CheckDuplicateRequest.FromString,
                    response_serializer=federation__pb2.CheckDuplicateResponse.SerializeToString,
            ),
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=federation__pb2.UploadChunk.FromString,
                    response_serializer=federation__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=federation__pb2.DownloadRequest.FromString,
                    response_serializer=federation__pb2.DownloadChunk.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=federation__pb2.ListObjectsRequest.FromString,
                    response_serializer=federation__pb2.ListObjectsResponse.SerializeToString,
            ),
            'ListPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPeers,
                    request_deserializer=federation__pb2.ListPeersRequest.FromString,
                    response_serializer=federation__pb2.ListPeersResponse.SerializeToString,
            ),
            'TransferFile': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFile,
                    request_deserializer=federation__pb2.TransferFileRequest.FromString,
                    response_serializer=federation__pb2.TransferFileResponse.SerializeToString,
            ),
            'PeerHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.PeerHealth,
                    request_deserializer=federation__pb2.PeerHealthRequest.FromString,
                    response_serializer=federation__pb2.PeerHealthResponse.SerializeToString,
            ),
            'AddPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPeer,
                    request_deserializer=federation__pb2.AddPeerRequest.FromString,
                    response_serializer=federation__pb2.AddPeerResponse.SerializeToString,
            ),
            'GetNodeInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeInfo,
                    request_deserializer=federation__pb2.GetNodeInfoRequest.FromString,
                    response_serializer=federation__pb2.GetNodeInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federation.v1.FederationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FederationService(object):
    """FederationService provides file storage and retrieval for the medical image federation.
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/Health',
            federation__pb2.HealthRequest.SerializeToString,
            federation__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckDuplicate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/CheckDuplicate',
            federation__pb2.CheckDuplicateRequest.SerializeToString,
            federation__pb2.CheckDuplicateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/federation.v1.FederationService/UploadFile',
            federation__pb2.UploadChunk.SerializeToString,
            federation__pb2.UploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/federation.v1.FederationService/DownloadFile',
            federation__pb2.DownloadRequest.SerializeToString,
            federation__pb2.DownloadChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/ListObjects',
            federation__pb2.ListObjectsRequest.SerializeToString,
            federation__pb2.ListObjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/ListPeers',
            federation__pb2.ListPeersRequest.SerializeToString,
            federation__pb2.ListPeersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TransferFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/TransferFile',
            federation__pb2.TransferFileRequest.SerializeToString,
            federation__pb2.TransferFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PeerHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/PeerHealth',
            federation__pb2.PeerHealthRequest.SerializeToString,
            federation__pb2.PeerHealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/AddPeer',
            federation__pb2.AddPeerRequest.SerializeToString,
            federation__pb2.AddPeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNodeInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/federation.v1.FederationService/GetNodeInfo',
            federation__pb2.GetNodeInfoRequest.SerializeToString,
            federation__pb2.GetNodeInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
